name: GitHub Actions Demo

on:
  push:           # запуск при каждом push
  workflow_dispatch:  # добавим возможность запуска вручную

jobs:
  daily-run:
    name: Daily Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Instal Dependes
        run: pip install -r requirements.txt
      - name: Run App
        run: python sms.py

      